query AnimeDetailQuery($id: Int) {
  Media(id: $id, type: ANIME) {
    id
    idMal
    title {
      romaji
      english
      native
    }
    coverImage {
      extraLarge
      large
      color
    }
    bannerImage
    description
    genres
    averageScore
    meanScore
    episodes
    duration
    status
    format
    season
    seasonYear
    nextAiringEpisode {
      airingAt
      episode
    }
    studios {
      edges {
        isMain
        node {
          id
          name
        }
      }
    }
    characters(sort: ROLE, perPage: 12) {
      edges {
        role
        node {
          id
          name {
            full
            native
          }
          image {
            large
            medium
          }
        }
      }
    }
    relations {
      edges {
        relationType
        node {
          id
          type
          title {
            romaji
          }
          coverImage {
            medium
          }
          format
          status
        }
      }
    }
    trailer {
      id
      site
      thumbnail
    }
    siteUrl
  }
}

query AnimeDetailByMalQuery($idMal: Int) {
  Media(idMal: $idMal, type: ANIME) {
    id
    title {
      romaji
      english
      native
    }
    coverImage {
      extraLarge
      large
      color
    }
    bannerImage
    description
    genres
    averageScore
    meanScore
    episodes
    duration
    status
    format
    season
    seasonYear
    nextAiringEpisode {
      airingAt
      episode
    }
    studios {
      edges {
        isMain
        node {
          id
          name
        }
      }
    }
    characters(sort: ROLE, perPage: 12) {
      edges {
        role
        node {
          id
          name {
            full
            native
          }
          image {
            large
            medium
          }
        }
      }
    }
    relations {
      edges {
        relationType
        node {
          id
          type
          title {
            romaji
          }
          coverImage {
            medium
          }
          format
          status
        }
      }
    }
    trailer {
      id
      site
      thumbnail
    }
    siteUrl
  }
}
